# Generated by Django 3.2.2 on 2021-05-07 11:18

from django.db import migrations

from triggers.python_extension import PythonExtension


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0001_initial'),
    ]

    operations = [
        PythonExtension()
    ]
