# Generated by Django 3.2.2 on 2021-05-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0002_auto_20210507_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount_sold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='book',
            name='amount_stock',
            field=models.IntegerField(default=20),
        ),
    ]
